/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title LED controlled via a push button
 * \abstract An LED is controlled via a push button.
 * \description Upon pressure of a push button, an LED is turned on and the LED is turned off when releasing the button.
 *              One port pin is configured as input for checking the push button state 
 *              and the other port pin is configured as output to control the LED.
 *
 * \name GPIO_LED_Button_1_KIT_TC275_LK
 * \version V1.0.0
 * \board AURIX TC275 lite Kit, KIT_AURIX_TC275_LITE, TC27xTP_D-Step
 * \keywords AURIX, GPIO, GPIO_LED_Button_1, LED, pin, port, port pin, push button, push-pull
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_GPIO_LED_Button_1_KIT_TC275_LK-TR-v01_00_00-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC27D_iLLD_UM_1_0_1_12_0.chm
 * \lastUpdated 2021-06-29
 *********************************************************************************************************************/
#include "btt6200.h"
#include "usart.h"
#include "stm.h"
#include "led.h"
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "switch.h"
#include "iso1i813t.h"
#include "dma.h"
#include "ccu6.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;



int core0_main(void)
{
    unsigned char rxbuf[256] = {0};
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    btt6200_init();
    Uart_Init(115200);
    led_init();
//    switch_init();
    STM0_channel0_Init(5000);
//    iso1i813t_init();
    btt6200_all_close();
    led_off();
    ccu6_init();
    int rx_count = 0;
    int i = 0;
    int j = 0;
    int read_count = 1;
//    IfxCcu6_Timer_start(&g_timer);
    while(1)
    {

        if(1 == g_rx_finsh) {
            rx_count = g_rx_count; // * 4 + IfxAsclin_getRxFifoFillLevel(g_ascHandle.asclin);
            my_printf("rx_count = %d\t", rx_count);
            // my_printf("rx_buf = %s\r\n", g_ascHandle.rx->buffer);

            if(rx_count != 50) {
                btt6200_all_open();
            }

            if(rx_count >= 256) {
                IfxAsclin_Asc_clearRx(&g_ascHandle);
                rx_count = 0;
                goto END;
            }

            for(j = 0; j < rx_count; j++)
            {
                IfxAsclin_Asc_read(&g_ascHandle, &rxbuf[j], (Ifx_SizeT*)&read_count, TIME_INFINITE);
            }
            END:
            // IfxAsclin_Asc_read(&g_ascHandle, rxbuf, &rx_count, TIME_INFINITE);
            // ASCLIN2_GetBuff(rxbuf, rx_count);
            my_printf("rx_buf = %s\r\n", rxbuf);
            g_rx_count = 0;
            memset(rxbuf, 0, sizeof(rxbuf));
            ASCLIN2_clearGetCount();
            g_rx_finsh = 0;
        }


        if(i == 500) {
//            my_printf("g_count = %d\t", g_rx_count);
//            my_printf("FILL = %d\t", IfxAsclin_getRxFifoFillLevel(g_ascHandle.asclin));
//            my_printf("%s\r\n", g_ascHandle.rx->buffer);
//            ASCLIN2_clearGetCount();
//            my_printf("g_counter = %d\r\n", g_count);
            led_toggled();
            i = 0;
        }

        delayms(1);
        i++;
    }
    return (1);
}
